// <auto-generated />
using System;
using DiscordCoopCodes.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiscordCoopCodes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191111183101_UpdateMessage")]
    partial class UpdateMessage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiscordCoopCodes.Database.Entities.Contract", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Created");

                    b.Property<string>("Description");

                    b.Property<DateTimeOffset>("GoodUntil");

                    b.Property<int>("MaxUsers");

                    b.Property<string>("Name");

                    b.Property<int>("P11");

                    b.Property<int>("P2");

                    b.Property<int>("P4");

                    b.Property<double>("P6");

                    b.Property<double>("P7");

                    b.Property<string>("Rewards");

                    b.Property<bool>("coop_allowed");

                    b.Property<bool>("debug");

                    b.Property<string>("egg");

                    b.Property<string>("goals");

                    b.Property<double>("length_seconds");

                    b.Property<int>("max_boosts");

                    b.Property<double>("max_soul_eggs");

                    b.Property<int>("min_client_version");

                    b.HasKey("ID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("DiscordCoopCodes.Database.Entities.Coop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContractID");

                    b.Property<DateTimeOffset?>("CoopEnds");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<int?>("CurrentUsers");

                    b.Property<bool>("DeletedChannel");

                    b.Property<decimal>("DiscordChannelId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<bool>("Finished");

                    b.Property<DateTimeOffset?>("LastUpdateToChannel");

                    b.Property<int?>("MaxUsers");

                    b.Property<string>("Name");

                    b.Property<bool>("ProjectedToFinish");

                    b.Property<string>("UpdateMessagesId");

                    b.Property<DateTimeOffset?>("WarningForDeleteChannel");

                    b.HasKey("Id");

                    b.HasIndex("ContractID");

                    b.ToTable("Coops");
                });

            modelBuilder.Entity("DiscordCoopCodes.Database.Entities.CoopStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Base64Data");

                    b.Property<Guid>("CoopId");

                    b.Property<DateTimeOffset>("Created");

                    b.HasKey("Id");

                    b.HasIndex("CoopId");

                    b.ToTable("CoopStatuses");
                });

            modelBuilder.Entity("DiscordCoopCodes.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreateOn");

                    b.Property<decimal>("DiscordId")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("DiscordUsername");

                    b.Property<DateTimeOffset>("LastSleepingNotification");

                    b.Property<string>("_eggIncIds");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiscordCoopCodes.Database.Entities.UserCoopStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CoopId");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("EggIncId");

                    b.Property<string>("EggIncName");

                    b.Property<double>("Rate");

                    b.Property<DateTimeOffset?>("SleepingWarning");

                    b.Property<double>("Total");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CoopId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCoopStatuses");
                });

            modelBuilder.Entity("DiscordCoopCodes.Database.Entities.UserCoopXref", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("CoopId");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.HasKey("UserId", "CoopId");

                    b.HasIndex("CoopId");

                    b.ToTable("UserCoopXrefs");
                });

            modelBuilder.Entity("DiscordCoopCodes.Database.Entities.Coop", b =>
                {
                    b.HasOne("DiscordCoopCodes.Database.Entities.Contract", "Contract")
                        .WithMany("Coops")
                        .HasForeignKey("ContractID");
                });

            modelBuilder.Entity("DiscordCoopCodes.Database.Entities.CoopStatus", b =>
                {
                    b.HasOne("DiscordCoopCodes.Database.Entities.Coop", "Coop")
                        .WithMany("CoopStatuses")
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DiscordCoopCodes.Database.Entities.UserCoopStatus", b =>
                {
                    b.HasOne("DiscordCoopCodes.Database.Entities.Coop", "Coop")
                        .WithMany()
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DiscordCoopCodes.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DiscordCoopCodes.Database.Entities.UserCoopXref", b =>
                {
                    b.HasOne("DiscordCoopCodes.Database.Entities.Coop", "Coop")
                        .WithMany("UserCoopsXrefs")
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DiscordCoopCodes.Database.Entities.User", "User")
                        .WithMany("UserCoopXrefs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
