// <auto-generated />
using System;
using EGG9000.Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EGG9000.Common.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200511210543_LastBackup")]
    partial class LastBackup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Contract", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("GoodUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("P11")
                        .HasColumnType("int");

                    b.Property<int>("P2")
                        .HasColumnType("int");

                    b.Property<int>("P4")
                        .HasColumnType("int");

                    b.Property<double>("P6")
                        .HasColumnType("float");

                    b.Property<double>("P7")
                        .HasColumnType("float");

                    b.Property<string>("Rewards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("coop_allowed")
                        .HasColumnType("bit");

                    b.Property<bool>("debug")
                        .HasColumnType("bit");

                    b.Property<string>("egg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("length_seconds")
                        .HasColumnType("float");

                    b.Property<int>("max_boosts")
                        .HasColumnType("int");

                    b.Property<double>("max_soul_eggs")
                        .HasColumnType("float");

                    b.Property<int>("min_client_version")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Coop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CoopEnds")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrentUsers")
                        .HasColumnType("int");

                    b.Property<bool>("DeletedChannel")
                        .HasColumnType("bit");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("JoinUsers")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastUpdateToChannel")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("League")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProjectedToFinish")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdateMessagesId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("WarningForDeleteChannel")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ContractID");

                    b.ToTable("Coops");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.CoopStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Base64Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CoopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CoopId");

                    b.ToTable("CoopStatuses");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Demerit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("When")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Demerit");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Event", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Ends")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Multiplier")
                        .HasColumnType("float");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.GuildContract", b =>
                {
                    b.Property<string>("ContractID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GuildID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("Elite")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("DeletedChannel")
                        .HasColumnType("bit");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("NumberOfCoops")
                        .HasColumnType("int");

                    b.Property<string>("Starters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("WarningForDeleteChannel")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ContractID", "GuildID", "Elite");

                    b.ToTable("GuildContracts");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AcceptedRules")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreateOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("DiscordUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("LastSleepingNotification")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("_LastBackup")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("_eggIncIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCoopStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EggIncId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EggIncName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("SleepingWarning")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CoopId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCoopStatuses");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCoopXref", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AddedToChannel")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("JoinedCoop")
                        .HasColumnType("bit");

                    b.Property<bool>("Starter")
                        .HasColumnType("bit");

                    b.Property<bool>("WaitingOnStarter")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "CoopId");

                    b.HasIndex("CoopId");

                    b.ToTable("UserCoopXrefs");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Coop", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Contract", "Contract")
                        .WithMany("Coops")
                        .HasForeignKey("ContractID");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.CoopStatus", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Coop", "Coop")
                        .WithMany("CoopStatuses")
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Demerit", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.User", "AdminUser")
                        .WithMany("DemeritsGiven")
                        .HasForeignKey("AdminUserId")
                        .IsRequired();

                    b.HasOne("EGG9000.Common.Database.Entities.User", "User")
                        .WithMany("Demerits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.GuildContract", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Contract", "Contract")
                        .WithMany("GuildContracts")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCoopStatus", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Coop", "Coop")
                        .WithMany()
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGG9000.Common.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCoopXref", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Coop", "Coop")
                        .WithMany("UserCoopsXrefs")
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGG9000.Common.Database.Entities.User", "User")
                        .WithMany("UserCoopXrefs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
