// <auto-generated />
using System;
using EGG9000.Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EGG9000.Common.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240319152029_CoopThreads")]
    partial class CoopThreads
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EGG9000.Common.Database.Entities.AutomationLog", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Skipped")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("AutomationLogs");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Contract", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("GoodUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("HadTwoRewards")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("P11")
                        .HasColumnType("int");

                    b.Property<int>("P2")
                        .HasColumnType("int");

                    b.Property<int>("P4")
                        .HasColumnType("int");

                    b.Property<double>("P6")
                        .HasColumnType("float");

                    b.Property<double>("P7")
                        .HasColumnType("float");

                    b.Property<string>("Rewards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("cc_only")
                        .HasColumnType("bit");

                    b.Property<bool>("coop_allowed")
                        .HasColumnType("bit");

                    b.Property<bool>("debug")
                        .HasColumnType("bit");

                    b.Property<string>("egg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("length_seconds")
                        .HasColumnType("float");

                    b.Property<int>("max_boosts")
                        .HasColumnType("int");

                    b.Property<double>("max_soul_eggs")
                        .HasColumnType("float");

                    b.Property<int>("min_client_version")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Coop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AnyLeague")
                        .HasColumnType("bit");

                    b.Property<string>("ContractID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CoopCompleted")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CoopEnds")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentUsers")
                        .HasColumnType("int");

                    b.Property<bool>("DeletedChannel")
                        .HasColumnType("bit");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("FindChannelErrors")
                        .HasColumnType("bigint");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<decimal>("Group")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("JoinUsers")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastUpdateToChannel")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("League")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OverflowGuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset?>("ProjectedFinish")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("ProjectedToFinish")
                        .HasColumnType("bit");

                    b.Property<bool>("PseudoExpired")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("ThreadArchived")
                        .HasColumnType("bit");

                    b.Property<decimal>("ThreadID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ThreadParentChannel")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("UpdateMessagesId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("WarningForDeleteChannel")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("_StatusCompressed")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContractID");

                    b.ToTable("Coops");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.DBUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AcceptedRules")
                        .HasColumnType("bit");

                    b.Property<bool>("Banned")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreateOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomCoopName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DMOnShipReturn")
                        .HasColumnType("bit");

                    b.Property<bool>("DMSBlocked")
                        .HasColumnType("bit");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("DiscordUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EIDs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ExpireCustomCoopName")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GuildCoops")
                        .HasColumnType("int");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("LastGuild")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("LastSleepingNotification")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("NextBreakExpire")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("NextShipReturnDMDue")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("OnBreakSince")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("Registered")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ServersBannedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShipReturnDMAfterFuel")
                        .HasColumnType("bit");

                    b.Property<int>("ShipReturnMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ShipReturnStillFuelingMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("SkipNoArtifacts")
                        .HasColumnType("bit");

                    b.Property<bool>("SkipNoPE")
                        .HasColumnType("bit");

                    b.Property<bool>("SkipNoPiggyDouble")
                        .HasColumnType("bit");

                    b.Property<bool>("TempDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Usernames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("_CustomBackups")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("_contractRegistrationByte")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("_coopSettingByte")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("_eggIncIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("_shipDMsByte")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("showEB")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Demerit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Permanent")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("When")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Demerit");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("When")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Event", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CcOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("Ended")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Ends")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Multiplier")
                        .HasColumnType("float");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.EventCustomization", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_settings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Type");

                    b.ToTable("EventCustomizations");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.ExpiringShell", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Expires")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Json")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("ExpiringShells");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.GlobalLeaderboardCoop", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CheckFailed")
                        .HasColumnType("bit");

                    b.Property<bool>("Checked")
                        .HasColumnType("bit");

                    b.Property<string>("ContractID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DegreeOfSeperation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("GlobalLeaderboardCoops");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.GlobalLeaderboardUser", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DegreeOfSeperation")
                        .HasColumnType("int");

                    b.Property<string>("EggIncId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastBackup")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastUpdate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("NeedsUpdate")
                        .HasColumnType("bit");

                    b.Property<bool>("UpdateFailed")
                        .HasColumnType("bit");

                    b.Property<double>("earnings_bonus")
                        .HasColumnType("float");

                    b.Property<decimal>("eggs_of_prophecy")
                        .HasColumnType("decimal(20,0)");

                    b.Property<double>("lifetime_cash_earned")
                        .HasColumnType("float");

                    b.Property<double>("soul_eggs")
                        .HasColumnType("float");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("GlobalLeaderboardUsers");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Guild", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<string>("ActiveElites")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActiveStandards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AllowGuilds")
                        .HasColumnType("bit");

                    b.Property<string>("CoopCategories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoopNamePrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisableBG")
                        .HasColumnType("bit");

                    b.Property<decimal>("DiscordSeverId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("FinishedCategories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupRoles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InactiveElites")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InactiveStandards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaderboardImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowServersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PublicScoreGrid")
                        .HasColumnType("bit");

                    b.Property<bool>("RemoveFindCoopSpot")
                        .HasColumnType("bit");

                    b.Property<string>("RolesToSync")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCoopsMessageDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_channelDetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_coopSettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_eventCustomizationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.GuildContract", b =>
                {
                    b.Property<string>("ContractID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GuildID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("League")
                        .HasColumnType("bigint");

                    b.Property<int>("BoardingGroup")
                        .HasColumnType("int");

                    b.Property<bool>("CcOnly")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("DeletedChannel")
                        .HasColumnType("bit");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("HasScores")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfCoops")
                        .HasColumnType("int");

                    b.Property<string>("OutsideCoops")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Starters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("WarningForDeleteChannel")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ContractID", "GuildID", "League");

                    b.ToTable("GuildContracts");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Merit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("When")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Merit");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.TemporaryRole", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Expires")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "RoleId", "Created");

                    b.ToTable("TemporaryRoles");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UpcomingContract", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("ContractId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GuildID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsLeggacy")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("TargetDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("_userRegs")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ID");

                    b.HasIndex("ContractId");

                    b.ToTable("UpcomingContracts");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCoopStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EggIncId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EggIncName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("SleepingWarning")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CoopId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCoopStatuses");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCoopXref", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EggIncId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AddedToChannel")
                        .HasColumnType("bit");

                    b.Property<bool>("CoopFullWarning")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EquipedTachyonDeflector")
                        .HasColumnType("bit");

                    b.Property<string>("FixedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Group")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("GussetCheatDetected")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTachyonDeflector")
                        .HasColumnType("bit");

                    b.Property<int>("HoursSleeping")
                        .HasColumnType("int");

                    b.Property<bool>("JoinWarning12h")
                        .HasColumnType("bit");

                    b.Property<bool>("JoinWarning24TillFinish")
                        .HasColumnType("bit");

                    b.Property<bool>("JoinWarning24h")
                        .HasColumnType("bit");

                    b.Property<bool>("JoinedCoop")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastStatusTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("NoDemerit")
                        .HasColumnType("bit");

                    b.Property<bool>("OutsideCoop")
                        .HasColumnType("bit");

                    b.Property<bool>("PingOnFinished")
                        .HasColumnType("bit");

                    b.Property<bool>("PingOnFull")
                        .HasColumnType("bit");

                    b.Property<bool>("PingOnHighestEB")
                        .HasColumnType("bit");

                    b.Property<string>("RefEggIncId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("RunningScore")
                        .HasColumnType("real");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<float?>("SiloTimeHours")
                        .HasColumnType("real");

                    b.Property<decimal>("SleepingDiscordMessageID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTimeOffset?>("SleepingWarningTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("SoulPower")
                        .HasColumnType("float");

                    b.Property<bool>("Starter")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TimeCheatReported")
                        .HasColumnType("bit");

                    b.Property<float>("TotalHoursSleeping")
                        .HasColumnType("real");

                    b.Property<bool>("WaitingOnStarter")
                        .HasColumnType("bit");

                    b.Property<bool>("WasAssigned")
                        .HasColumnType("bit");

                    b.Property<byte[]>("_coopSettingByte")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("_lastStatusByte")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("_sleepTrackingByte")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("UserId", "CoopId", "EggIncId");

                    b.HasIndex("CoopId");

                    b.HasIndex("CreatedOn", "JoinedCoop");

                    b.ToTable("UserCoopXrefs");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCsHistoryEntry", b =>
                {
                    b.Property<string>("CoopIdentifier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContractIdentifier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EggIncId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Cxp")
                        .HasColumnType("float");

                    b.HasKey("CoopIdentifier", "ContractIdentifier", "EggIncId");

                    b.ToTable("UserCsHistoryEntries");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserSnapShot", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("EggIncID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("EarningsBonus")
                        .HasColumnType("float");

                    b.Property<decimal>("EggsOfProphecy")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("Prestiges")
                        .HasColumnType("decimal(20,0)");

                    b.Property<double>("SoulEggs")
                        .HasColumnType("float");

                    b.HasKey("UserId", "Date", "EggIncID");

                    b.ToTable("UserSnapShots");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Coop", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Contract", "Contract")
                        .WithMany("Coops")
                        .HasForeignKey("ContractID");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Demerit", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "AdminUser")
                        .WithMany("DemeritsGiven")
                        .HasForeignKey("AdminUserId")
                        .IsRequired();

                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "User")
                        .WithMany("Demerits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Donation", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.GuildContract", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Contract", "Contract")
                        .WithMany("GuildContracts")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Merit", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "AdminUser")
                        .WithMany("MeritsGiven")
                        .HasForeignKey("AdminUserId")
                        .IsRequired();

                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "User")
                        .WithMany("Merits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UpcomingContract", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCoopStatus", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Coop", "Coop")
                        .WithMany()
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Coop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCoopXref", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Coop", "Coop")
                        .WithMany("UserCoopsXrefs")
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "User")
                        .WithMany("UserCoopXrefs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Contract", b =>
                {
                    b.Navigation("Coops");

                    b.Navigation("GuildContracts");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Coop", b =>
                {
                    b.Navigation("UserCoopsXrefs");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.DBUser", b =>
                {
                    b.Navigation("Demerits");

                    b.Navigation("DemeritsGiven");

                    b.Navigation("Merits");

                    b.Navigation("MeritsGiven");

                    b.Navigation("UserCoopXrefs");
                });
#pragma warning restore 612, 618
        }
    }
}
