// <auto-generated />
using System;
using EGG9000.Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EGG9000.Common.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260622044356_AddShadowAssignmentDiff")]
    partial class AddShadowAssignmentDiff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EGG9000.Common.Database.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.AutomationLog", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Skipped")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("AutomationLogs");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Contract", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("GoodUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HadTwoRewards")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("P11")
                        .HasColumnType("integer");

                    b.Property<int>("P2")
                        .HasColumnType("integer");

                    b.Property<int>("P4")
                        .HasColumnType("integer");

                    b.Property<double>("P6")
                        .HasColumnType("double precision");

                    b.Property<double>("P7")
                        .HasColumnType("double precision");

                    b.Property<string>("Rewards")
                        .HasColumnType("text");

                    b.Property<string>("_response")
                        .HasColumnType("text");

                    b.Property<bool>("cc_only")
                        .HasColumnType("boolean");

                    b.Property<bool>("coop_allowed")
                        .HasColumnType("boolean");

                    b.Property<bool>("debug")
                        .HasColumnType("boolean");

                    b.Property<string>("egg")
                        .HasColumnType("text");

                    b.Property<double>("egg_value")
                        .HasColumnType("double precision");

                    b.Property<string>("goals")
                        .HasColumnType("text");

                    b.Property<double>("length_seconds")
                        .HasColumnType("double precision");

                    b.Property<int>("max_boosts")
                        .HasColumnType("integer");

                    b.Property<double>("max_soul_eggs")
                        .HasColumnType("double precision");

                    b.Property<int>("min_client_version")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Coop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AddedFromBackup")
                        .HasColumnType("boolean");

                    b.Property<bool>("AnyLeague")
                        .HasColumnType("boolean");

                    b.Property<string>("ContractID")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CoopCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CoopEnds")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorID")
                        .HasColumnType("text");

                    b.Property<int?>("CurrentUsers")
                        .HasColumnType("integer");

                    b.Property<bool>("DeletedChannel")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("FindChannelErrors")
                        .HasColumnType("bigint");

                    b.Property<bool>("Finished")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Group")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("JoinUsers")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastUpdateToChannel")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("League")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("OverflowGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset?>("ProjectedFinish")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ProjectedToFinish")
                        .HasColumnType("boolean");

                    b.Property<bool>("PseudoExpired")
                        .HasColumnType("boolean");

                    b.Property<bool>("RolesAddedToThread")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("SuccessfullyStarted")
                        .HasColumnType("boolean");

                    b.Property<bool>("ThreadArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ThreadID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ThreadParentChannel")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UpdateMessagesId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("WarningForDeleteChannel")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("_StatusCompressed")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ContractID");

                    b.HasIndex("Status");

                    b.HasIndex("ThreadID");

                    b.HasIndex("ThreadID", "Created");

                    b.HasIndex("GuildId", "ContractID", "League")
                        .HasFilter("NOT \"Finished\" AND NOT \"DeletedChannel\" AND NOT \"ThreadArchived\"");

                    b.HasIndex("DiscordChannelId", "ThreadArchived", "CoopEnds", "ThreadID");

                    b.ToTable("Coops");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.DBCustomEgg", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("EmojiId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("EmojiName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Released")
                        .HasColumnType("boolean");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.Property<byte[]>("_iconBytes")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("_modifiersBytes")
                        .HasColumnType("bytea");

                    b.HasKey("Identifier");

                    b.ToTable("CustomEggs");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.DBUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AcceptedRules")
                        .HasColumnType("boolean");

                    b.Property<bool>("Banned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreateOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomCoopName")
                        .HasColumnType("text");

                    b.Property<bool>("DMOnShipReturn")
                        .HasColumnType("boolean");

                    b.Property<bool>("DMSBlocked")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("DiscordUsername")
                        .HasColumnType("text");

                    b.Property<string>("EIDs")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpireCustomCoopName")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GuildCoops")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("HighestAnnouncedOom")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastBackupCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastFAQPosted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LastGuild")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSleepingNotification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextBreakExpire")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextShipReturnDMDue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("OnBreakSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Registered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServersBannedFrom")
                        .HasColumnType("text");

                    b.Property<bool>("ShipReturnDMAfterFuel")
                        .HasColumnType("boolean");

                    b.Property<int>("ShipReturnMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ShipReturnStillFuelingMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("SkipNoArtifacts")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkipNoPE")
                        .HasColumnType("boolean");

                    b.Property<bool>("SkipNoPiggyDouble")
                        .HasColumnType("boolean");

                    b.Property<bool>("TempDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Usernames")
                        .HasColumnType("text");

                    b.Property<byte[]>("_CustomBackups")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("_contractRegistrationByte")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("_coopSettingByte")
                        .HasColumnType("bytea");

                    b.Property<string>("_eggIncIds")
                        .HasColumnType("text");

                    b.Property<byte[]>("_shipDMsByte")
                        .HasColumnType("bytea");

                    b.Property<bool>("showEB")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId");

                    b.HasIndex("LastBackupCheck");

                    b.HasIndex("LastModified");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Demerit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractID")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<bool>("Permanent")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("When")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Demerit");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("When")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Event", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CcOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ended")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Ends")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<string>("MessageIds")
                        .HasColumnType("text");

                    b.Property<double>("Multiplier")
                        .HasColumnType("double precision");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.EventCustomization", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .HasColumnType("text");

                    b.Property<string>("Fields")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailURL")
                        .HasColumnType("text");

                    b.Property<string>("_settings")
                        .HasColumnType("text");

                    b.HasKey("Type");

                    b.ToTable("EventCustomizations");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.ExpiringShell", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<string>("Json")
                        .HasColumnType("text");

                    b.Property<string>("MessageIds")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("ExpiringShells");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.FAQTopic", b =>
                {
                    b.Property<string>("InternalId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("CreatedById")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("CreatedByIdString")
                        .HasColumnType("text");

                    b.Property<string>("EmbedColorHex")
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GuildIdString")
                        .HasColumnType("text");

                    b.Property<string>("GuildName")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("PalaceOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("StaffOnly")
                        .HasColumnType("boolean");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<string>("_keywords")
                        .HasColumnType("text");

                    b.Property<string>("_subscribedGuildIds")
                        .HasColumnType("text");

                    b.HasKey("InternalId");

                    b.ToTable("FAQTopics");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.GlobalLeaderboardCoop", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CheckFailed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Checked")
                        .HasColumnType("boolean");

                    b.Property<string>("ContractID")
                        .HasColumnType("text");

                    b.Property<int>("DegreeOfSeperation")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("GlobalLeaderboardCoops");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.GlobalLeaderboardUser", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DegreeOfSeperation")
                        .HasColumnType("integer");

                    b.Property<string>("EggIncId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastBackup")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NeedsUpdate")
                        .HasColumnType("boolean");

                    b.Property<bool>("UpdateFailed")
                        .HasColumnType("boolean");

                    b.Property<double>("earnings_bonus")
                        .HasColumnType("double precision");

                    b.Property<decimal>("eggs_of_prophecy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<double>("lifetime_cash_earned")
                        .HasColumnType("double precision");

                    b.Property<double>("soul_eggs")
                        .HasColumnType("double precision");

                    b.Property<string>("user_id")
                        .HasColumnType("text");

                    b.Property<string>("user_name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("GlobalLeaderboardUsers");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Guild", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ActiveElites")
                        .HasColumnType("text");

                    b.Property<string>("ActiveStandards")
                        .HasColumnType("text");

                    b.Property<bool>("AddOutsideCoops")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowGuilds")
                        .HasColumnType("boolean");

                    b.Property<string>("CoopCategories")
                        .HasColumnType("text");

                    b.Property<string>("CoopNamePrefix")
                        .HasColumnType("text");

                    b.Property<bool>("DisableBG")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DiscordSeverId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("FAQTopicCooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("FAQTopicsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FinishedCategories")
                        .HasColumnType("text");

                    b.Property<string>("GroupRoles")
                        .HasColumnType("text");

                    b.Property<string>("InactiveElites")
                        .HasColumnType("text");

                    b.Property<string>("InactiveStandards")
                        .HasColumnType("text");

                    b.Property<string>("LeaderboardImage")
                        .HasColumnType("text");

                    b.Property<float>("MinimumRunningScore")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OverflowServersJson")
                        .HasColumnType("text");

                    b.Property<bool>("PublicScoreGrid")
                        .HasColumnType("boolean");

                    b.Property<bool>("RankupExclusivePool")
                        .HasColumnType("boolean");

                    b.Property<bool>("RankupMessagesEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("RemoveFindCoopSpot")
                        .HasColumnType("boolean");

                    b.Property<string>("RolesToSync")
                        .HasColumnType("text");

                    b.Property<bool>("ShowContractStatsEmbeds")
                        .HasColumnType("boolean");

                    b.Property<string>("StaffCoopsMessageDetails")
                        .HasColumnType("text");

                    b.Property<string>("_channelDetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("_coopSettingsJson")
                        .HasColumnType("text");

                    b.Property<string>("_eventCustomizationsJson")
                        .HasColumnType("text");

                    b.Property<string>("_faqTopicsJson")
                        .HasColumnType("text");

                    b.Property<string>("_rankupDisabledGroupsCsv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordSeverId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.GuildContract", b =>
                {
                    b.Property<string>("ContractID")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("League")
                        .HasColumnType("bigint");

                    b.Property<int>("BoardingGroup")
                        .HasColumnType("integer");

                    b.Property<bool>("CcOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeletedChannel")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("HasScores")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfCoops")
                        .HasColumnType("integer");

                    b.Property<string>("OutsideCoops")
                        .HasColumnType("text");

                    b.Property<bool>("ReadyToScore")
                        .HasColumnType("boolean");

                    b.Property<string>("Skip")
                        .HasColumnType("text");

                    b.Property<string>("Starters")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("WarningForDeleteChannel")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ContractID", "GuildID", "League");

                    b.HasIndex("DiscordChannelId");

                    b.ToTable("GuildContracts");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Merit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("When")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Merit");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.NasaApod", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Copyright")
                        .HasColumnType("text");

                    b.Property<string>("DateString")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("TO_CHAR(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD')");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("HdUrl")
                        .HasColumnType("text");

                    b.Property<string>("MediaType")
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<byte[]>("_postedToBytes")
                        .HasColumnType("bytea");

                    b.HasKey("ID");

                    b.ToTable("NasaApods");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.RankupMessage", b =>
                {
                    b.Property<string>("InternalId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("CreatedById")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("CreatedByIdString")
                        .HasColumnType("text");

                    b.Property<int>("GroupBaseOom")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GuildName")
                        .HasColumnType("text");

                    b.Property<bool>("PalaceOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<string>("_subscribedGuildIds")
                        .HasColumnType("text");

                    b.HasKey("InternalId");

                    b.ToTable("RankupMessages");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.ResearchCostSubmission", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID", "Level", "UserId");

                    b.ToTable("ResearchCostSubmissions");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.SeasonInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GoalsJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SeasonInfos");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.ShadowAssignmentDiff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContractId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("EggIncId")
                        .HasColumnType("text");

                    b.Property<bool>("ExpectedSeasonalDeviation")
                        .HasColumnType("boolean");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("LiveAssigned")
                        .HasColumnType("boolean");

                    b.Property<string>("LiveReason")
                        .HasColumnType("text");

                    b.Property<bool>("ShadowAssigned")
                        .HasColumnType("boolean");

                    b.Property<string>("ShadowReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShadowAssignmentDiffs");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.TemporaryRole", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId", "Created");

                    b.ToTable("TemporaryRoles");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UpcomingContract", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ContractId")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsLeggacy")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("TargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("_userRegs")
                        .HasColumnType("bytea");

                    b.HasKey("ID");

                    b.HasIndex("ContractId");

                    b.ToTable("UpcomingContracts");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCoopStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoopId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EggIncId")
                        .HasColumnType("text");

                    b.Property<string>("EggIncName")
                        .HasColumnType("text");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("SleepingWarning")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoopId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCoopStatuses");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCoopXref", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoopId")
                        .HasColumnType("uuid");

                    b.Property<string>("EggIncId")
                        .HasColumnType("text");

                    b.Property<bool>("AddedToChannel")
                        .HasColumnType("boolean");

                    b.Property<bool>("CoopFullWarning")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EquipedTachyonDeflector")
                        .HasColumnType("boolean");

                    b.Property<string>("FixedUserName")
                        .HasColumnType("text");

                    b.Property<decimal>("Group")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("GussetCheatDetected")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTachyonDeflector")
                        .HasColumnType("boolean");

                    b.Property<int>("HoursSleeping")
                        .HasColumnType("integer");

                    b.Property<bool>("JoinWarning12h")
                        .HasColumnType("boolean");

                    b.Property<bool>("JoinWarning24TillFinish")
                        .HasColumnType("boolean");

                    b.Property<bool>("JoinWarning24h")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("Joined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("JoinedCoop")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastStatusTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NoDemerit")
                        .HasColumnType("boolean");

                    b.Property<bool>("OutsideCoop")
                        .HasColumnType("boolean");

                    b.Property<bool>("PingOnFinished")
                        .HasColumnType("boolean");

                    b.Property<bool>("PingOnFull")
                        .HasColumnType("boolean");

                    b.Property<bool>("PingOnHighestEB")
                        .HasColumnType("boolean");

                    b.Property<string>("RefEggIncId")
                        .HasColumnType("text");

                    b.Property<float?>("RunningScore")
                        .HasColumnType("real");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<float?>("SiloTimeHours")
                        .HasColumnType("real");

                    b.Property<decimal>("SleepingDiscordMessageID")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset?>("SleepingWarningTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("SoulPower")
                        .HasColumnType("double precision");

                    b.Property<bool>("Starter")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<bool>("TimeCheatReported")
                        .HasColumnType("boolean");

                    b.Property<float>("TotalHoursSleeping")
                        .HasColumnType("real");

                    b.Property<bool>("WaitingOnStarter")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasAssigned")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("_coopSettingByte")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("_lastStatusByte")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("_sleepTrackingByte")
                        .HasColumnType("bytea");

                    b.HasKey("UserId", "CoopId", "EggIncId");

                    b.HasIndex("CoopId");

                    b.HasIndex("JoinedCoop");

                    b.HasIndex("CreatedOn", "JoinedCoop");

                    b.HasIndex("JoinedCoop", "CreatedOn");

                    b.HasIndex("UserId", "JoinedCoop");

                    b.ToTable("UserCoopXrefs");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCsHistoryEntry", b =>
                {
                    b.Property<string>("CoopIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("ContractIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("EggIncId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Cxp")
                        .HasColumnType("double precision");

                    b.HasKey("CoopIdentifier", "ContractIdentifier", "EggIncId");

                    b.HasIndex("ContractIdentifier");

                    b.ToTable("UserCsHistoryEntries");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserSeasonProgress", b =>
                {
                    b.Property<string>("EggIncId")
                        .HasColumnType("text");

                    b.Property<string>("SeasonId")
                        .HasColumnType("text");

                    b.Property<int>("StartingGrade")
                        .HasColumnType("integer");

                    b.Property<double>("TotalCxp")
                        .HasColumnType("double precision");

                    b.HasKey("EggIncId", "SeasonId");

                    b.ToTable("UserSeasonProgresses");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserSnapShot", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("EggIncID")
                        .HasColumnType("text");

                    b.Property<double>("EarningsBonus")
                        .HasColumnType("double precision");

                    b.Property<decimal>("EggsOfProphecy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("EggsOfTruth")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Prestiges")
                        .HasColumnType("numeric(20,0)");

                    b.Property<double>("SoulEggs")
                        .HasColumnType("double precision");

                    b.HasKey("UserId", "Date", "EggIncID");

                    b.ToTable("UserSnapShots");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Coop", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Contract", "Contract")
                        .WithMany("Coops")
                        .HasForeignKey("ContractID");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Demerit", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "AdminUser")
                        .WithMany("DemeritsGiven")
                        .HasForeignKey("AdminUserId");

                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "User")
                        .WithMany("Demerits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Donation", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.GuildContract", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Contract", "Contract")
                        .WithMany("GuildContracts")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Merit", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "AdminUser")
                        .WithMany("MeritsGiven")
                        .HasForeignKey("AdminUserId");

                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "User")
                        .WithMany("Merits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UpcomingContract", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCoopStatus", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Coop", "Coop")
                        .WithMany()
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Coop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.UserCoopXref", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.Coop", "Coop")
                        .WithMany("UserCoopsXrefs")
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGG9000.Common.Database.Entities.DBUser", "User")
                        .WithMany("UserCoopXrefs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGG9000.Common.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EGG9000.Common.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Contract", b =>
                {
                    b.Navigation("Coops");

                    b.Navigation("GuildContracts");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.Coop", b =>
                {
                    b.Navigation("UserCoopsXrefs");
                });

            modelBuilder.Entity("EGG9000.Common.Database.Entities.DBUser", b =>
                {
                    b.Navigation("Demerits");

                    b.Navigation("DemeritsGiven");

                    b.Navigation("Merits");

                    b.Navigation("MeritsGiven");

                    b.Navigation("UserCoopXrefs");
                });
#pragma warning restore 612, 618
        }
    }
}
