<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <LangVersion>preview</LangVersion>
    <Configurations>Debug;Release;DEV9002;DEV9001</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.5.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.5.1" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.16.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EGG9000.Common\EGG9000.Common.csproj" />
    <ProjectReference Include="..\EGG9000.Bot\EGG9000.Bot.csproj" />
  </ItemGroup>
</Project>
